### PR TITLE
db: Restore sqlite support

### PR DESCRIPTION
**Pull request by dubek**
1. Fix bug on sqlite with nullable columns
2. Add sqlite testing to run_local_tests
3. Add CI job for testing with sqlite

Signed-off-by: Dov Murik <dov.murik1@il.ibm.com>

---

I will rebase this PR on top of #51 after that is merged.

### CODE REVIEW

**Comment by dubek** [comment]
All tests pass except lint (clippy), which warns about needless-borrows in unrelated code.

**Comment by dubek** [comment]
Let's merge #53 first (fixes the clippy/lint warnings), and then I'll rebase this.

**Comment by dubek** [comment]
BTW the fix for the nullable fields was to convert (`try_get`) the DB value to `Option<i64>` instead of `i64`, which will properly convert the NULL to None. See https://docs.rs/sqlx/latest/sqlx/mysql/types/index.html#nullable .

**Review by fitzthum — APPROVED** [review]
LGTM.

**Comment by dubek** [comment]
Rebased on top of main; now CI is green.

**Pull request merged**
